"""Add interests column to users table

Revision ID: 1522973e4ef3
Revises: 73f7904d58a7
Create Date: 2025-03-26 02:42:34.650655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1522973e4ef3'
down_revision = '73f7904d58a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learners')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('user')
    op.drop_table('organizers')
    op.drop_table('sponsors')
    op.drop_table('speakers')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('admin_level',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('attendees', schema=None) as batch_op:
        batch_op.drop_column('organization')

    with op.batch_alter_table('stakeholders', schema=None) as batch_op:
        batch_op.drop_column('organization')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interests', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('interests')

    with op.batch_alter_table('stakeholders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization', mysql.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('attendees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization', mysql.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('admin_level',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    op.create_table('speakers',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('student_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('institution', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['attendees.id'], name='speakers_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('sponsors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('student_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('institution', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['stakeholders.id'], name='sponsors_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('organizers',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('student_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('institution', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['stakeholders.id'], name='organizers_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('learners',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('student_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('institution', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['attendees.id'], name='learners_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
