"""Add speaker, stakeholder, organizer and event_type columns

Revision ID: 73f7904d58a7
Revises: 7694e956ec81
Create Date: 2025-03-25 13:43:34.887966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '73f7904d58a7'
down_revision = '7694e956ec81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('speaker', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('stakeholder', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('organizer', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('event_type', sa.String(length=50), nullable=False))
        batch_op.alter_column('eventdescription',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('eventdescription',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('event_type')
        batch_op.drop_column('organizer')
        batch_op.drop_column('stakeholder')
        batch_op.drop_column('speaker')

    # ### end Alembic commands ###
